К сожалению, я так и не смог допилить проект, из-за возникших трудностей, прошу подсказать мне их разрешение, для того, чтобы я смог завершить его.

In [2]:
import pandas as pd
import numpy as np
import faiss
from tqdm.notebook import tqdm
from sklearn.metrics import top_k_accuracy_score
from catboost import CatBoostClassifier
from sklearn.model_selection import GridSearchCV

In [3]:
df_base = pd.read_csv("C:/Users/Администратор/Desktop/Андрей/Datasets/matching/base.csv", index_col=0)
df_train = pd.read_csv("C:/Users/Администратор/Desktop/Андрей/Datasets/matching/train.csv", index_col=0)
df_validation = pd.read_csv("C:/Users/Администратор/Desktop/Андрей/Datasets/matching/validation.csv", index_col=0)
df_validation_answer = pd.read_csv("C:/Users/Администратор/Desktop/Андрей/Datasets/matching/validation_answer.csv", index_col=0)

In [4]:
df_validation

,0,1,2,3,4,5,6,7,8,9,...,62,63,64,65,66,67,68,69,70,71
Id,,,,,,,,,,,,,,,,,,,,,
100000-query,-57.372734,3.597752,-13.213642,-125.926790,110.745940,-81.279594,-461.003172,139.815720,112.880980,75.215750,...,-75.513020,52.830902,-143.43945,59.051935,69.28224,61.927513,111.592530,115.140656,-1099.130485,-117.079360
100001-query,-53.758705,12.790300,-43.268543,-134.417620,114.449910,-90.520130,-759.626065,63.995087,127.117905,53.128998,...,-79.441830,29.185436,-168.60590,-82.872443,70.76560,-65.975950,97.077160,123.391640,-744.442332,-25.009320
100002-query,-64.175095,-3.980927,-7.679249,-170.160930,96.446160,-62.377740,-759.626065,87.477554,131.270110,168.920320,...,-134.795410,37.368730,-159.66231,-119.232725,67.71044,86.002060,137.636410,141.081630,-294.052271,-70.969604
100003-query,-99.286860,16.123936,9.837166,-148.060440,83.697080,-133.729720,58.576403,-19.046660,115.042404,75.206730,...,-77.236110,44.100494,-132.53012,-106.318982,70.88396,23.577892,133.183960,143.252940,-799.363667,-89.392670
100004-query,-79.532920,-0.364173,-16.027431,-170.884950,165.453920,-28.291668,33.931936,34.411217,128.903980,102.086914,...,-123.770250,45.635944,-134.25893,13.735359,70.61763,15.332115,154.568120,101.700640,-1171.892332,-125.307890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995-query,-46.672780,6.644193,7.376480,-116.126400,80.031715,-48.248695,-17.696937,108.150240,122.729744,103.643906,...,-65.641110,62.823895,-148.86781,-66.402868,66.99333,76.524155,66.525670,112.273720,-177.375834,-82.804726
199996-query,-94.786316,10.852646,13.700245,-125.619385,21.545967,-89.625534,79.880236,-46.513206,123.578730,74.033020,...,-65.032900,38.019740,-113.62750,-18.436499,64.16223,-117.032380,94.026490,86.279526,-1271.502930,-63.491104
199997-query,-59.224453,13.585838,22.655106,-134.926030,145.205690,-63.278100,-109.805058,16.277431,128.150040,168.835420,...,-48.826626,39.679783,-149.33646,160.609919,71.55922,25.237282,-35.985450,97.924790,73.080770,-28.081186
199998-query,-33.353630,11.671304,-31.577808,-127.493970,75.580860,-36.508230,-759.626065,-80.221510,123.711910,32.942696,...,-66.512146,15.792774,-143.07475,138.192370,68.22584,115.506546,-37.607803,149.608570,-173.070396,-60.923080
199999-query,-40.757560,6.832712,-29.993444,-156.309200,108.846780,-59.340584,-603.133148,-42.484253,119.490900,54.073837,...,-81.463290,28.412325,-171.74120,96.704654,66.79330,0.089361,175.958590,131.007740,-618.555199,-33.217857

In [5]:
dims = df_base.shape[1]
n_cells = 100
# how many cells
quantizer = faiss.IndexFlatL2(dims)
idx_l2 = faiss.IndexIVFFlat(quantizer, dims, n_cells)

In [6]:
idx_l2.train(np.ascontiguousarray(df_base.values[:50000, :]).astype('float32'))

idx_l2.add(np.ascontiguousarray(df_base.values).astype('float32'))

In [7]:
base_index = {k: v for k, v in enumerate(df_base.index.to_list())}

In [8]:
targets_train = df_train["Target"]
df_train.drop("Target", axis=1, inplace=True)

In [9]:
vecs, idx = idx_l2.search(np.ascontiguousarray(df_train.values).astype('float32'), 500)

In [10]:
total_acc = 0
acc = 0
alt_train_target = []
for target, el in zip(targets_train.values.tolist(), idx.tolist()):
    acc = int(target in [base_index[r] for r in el])
    alt_train_target.append(acc)
    total_acc += acc
print(100 * total_acc / len(idx))

9.23

In [11]:
dict={}
for i in range(len(targets_train)):
  dict[targets_train[i]] =  idx[i]

Первый проблемный момент, я не понял, как сделать accuracy@5

In [12]:
model = CatBoostClassifier(random_state = 21,logging_level='Silent')
cat_grid = {'depth':[1,3,5],
          'iterations':[250,100,500],
          'learning_rate':[0.01,0.1,0.3]}
model_grid = GridSearchCV(model,param_grid=cat_grid,cv=3,scoring='accuracy')
model_grid.fit(vecs,alt_train_target)
score = model_grid.predict(vecs)
print('Лучшие гиперпараметры: '+str(model_grid.best_params_))
print('Лучший результат: '+str(model_grid.best_score_))
print(top_k_accuracy_score(alt_train_target,score,k=5))

Лучшие гиперпараметры: {'depth': 5, 'iterations': 250, 'learning_rate': 0.1}
Лучший результат: 0.9432400026886212
1.0

C:\Anaconda\lib\site-packages\sklearn\metrics\_ranking.py:1777: UndefinedMetricWarning: 'k' (5) greater than or equal to 'n_classes' (2) will result in a perfect score and is therefore meaningless.
  warnings.warn(

In [14]:
idx_l2_valid = faiss.IndexIVFFlat(quantizer, dims, n_cells)
idx_l2_valid.train(np.ascontiguousarray(df_base.values[100000:, :199999]).astype('float32'))
idx_l2_valid.add(np.ascontiguousarray(df_base.values).astype('float32'))

In [15]:
vecs_valid, idx_valid = idx_l2_valid.search(np.ascontiguousarray(df_validation.values).astype('float32'), 1000)

,0,1,2,3,4,5,6,7,8,9,...,62,63,64,65,66,67,68,69,70,71
Id,,,,,,,,,,,,,,,,,,,,,
0-base,-115.083890,11.152912,-64.426760,-118.88089,216.482440,-104.698060,-469.070588,44.348083,120.915344,181.449700,...,-42.808693,38.800827,-151.762180,-74.389090,63.666340,-4.703861,92.933610,115.269190,-112.756640,-60.830353
1-base,-34.562202,13.332763,-69.787610,-166.53348,57.680607,-86.098370,-85.076666,-35.637436,119.718636,195.234190,...,-117.767525,41.100000,-157.829400,-94.446806,68.202110,24.346846,179.937930,116.834000,-84.888941,-59.524610
2-base,-54.233746,6.379371,-29.210136,-133.41383,150.895830,-99.435326,52.554795,62.381706,128.951450,164.381470,...,-76.397800,46.011803,-207.144420,127.325570,65.566180,66.325680,81.073490,116.594154,-1074.464888,-32.527206
3-base,-87.520130,4.037884,-87.803030,-185.06763,76.369540,-58.985165,-383.182845,-33.611237,122.031910,136.233580,...,-70.647940,-6.358921,-147.201050,-37.692750,66.202890,-20.566910,137.206940,117.474100,-1074.464888,-72.915490
4-base,-72.743850,6.522049,43.671265,-140.60803,5.820023,-112.074080,-397.711282,45.182500,122.167180,112.119064,...,-57.199104,56.642403,-159.351840,85.944724,66.766320,-2.505783,65.315285,135.051590,-1074.464888,0.319401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208834-base,-87.454500,2.591188,-11.951885,-156.80222,51.492256,-63.192795,-569.783053,12.046607,122.437805,143.380050,...,-38.294575,49.226994,-131.366960,14.652428,70.043655,79.429596,83.008760,127.809460,-1074.464888,-97.368280
208835-base,-109.982124,10.814451,-39.332910,-128.00850,172.408040,-26.220978,-399.238430,86.547550,117.790470,149.906510,...,-104.875470,28.288404,-115.980576,-39.667012,68.651390,66.225570,45.982250,148.029560,-1074.464888,-56.563023
208836-base,-62.149857,7.061927,-59.585810,-143.97539,130.500470,-131.254470,-426.861667,-53.140810,119.343666,152.239780,...,-37.460323,63.972610,-134.106720,-71.713724,66.899956,-18.376736,114.481920,113.858120,-668.721361,-141.898800
208837-base,-73.761116,5.890629,-41.066600,-150.31915,132.585970,-63.351727,-403.105290,102.740456,125.075250,119.330130,...,-61.165546,9.541286,-88.814060,0.981058,66.856575,-10.634670,107.042656,92.784560,-643.965757,10.088982
208838-base,-102.005410,5.317484,-35.490490,-162.27573,121.295364,-72.692795,-234.525012,-59.200134,120.937320,239.823820,...,-129.229520,34.865410,-191.495090,139.262559,68.965520,-16.812943,154.886500,128.893500,-883.546149,-75.427185

Второй проблемный момент, не понятно как правильно настроить таргет

In [18]:
total_acc = 0
acc = 0
alt_valid_target = []
for target, el in zip(df_validation_answer.values.tolist(), idx_valid.tolist()):
    acc = int(target in [base_index[r] for r in el])
    alt_valid_target.append(acc)
    total_acc += acc
print(100 * total_acc / len(idx_valid))

0.0